_target_: experiments.top_reco.wrappers.RecoGATrWrapper
force_xformers: '${training.force_xformers}'

net:
 _target_: gatr.nets.GATr

 in_mv_channels: 1
 out_mv_channels: 2
 hidden_mv_channels: 4

 in_s_channels: 0
 out_s_channels: 0
 hidden_s_channels: 8

 num_blocks: 1
 reinsert_mv_channels: null
 reinsert_s_channels: null
 dropout_prob: null
 double_layernorm: false

 attention:
  num_heads: 2
  multi_query: false
  increase_hidden_channels: 2
  head_scale: false

defaults:
 - /base_attention@net.attention
 - /base_mlp@net.mlp
