data:
 beam_reference: spacelike
 two_beams: true
 beam_token: true
 add_time_reference: true
 add_pt: false
 reinsert_channels: false

train: true
training:
 iterations: 1 #2500
 batchsize: 256
 lr: 1e-4
 scheduler: ReduceLROnPlateau
 validate_every_n_steps: 1 #500

 force_xformers: false

evaluation:
 batchsize: 256
 save_roc: false
 eval_set: [val]

plotting:
 roc: true
 loss: true
 score: true
 pt_dist: true
 pt_1dist: true

defaults:
 - model: gatr_reco
 - default
