data:
 beam_reference: spacelike
 two_beams: true
 beam_token: true
 add_time_reference: true
 add_pt: false
 reinsert_channels: false

train: true
training:
 iterations: 15000
 batchsize: 256
 lr: 1e-4
 optimizer: ScheduleFree
 validate_every_n_steps: 5000

 force_xformers: false
 scalar_target: false
 lambdaloss: 10

evaluation:
 batchsize: 128
 save_roc: false
 eval_set: [val]

plotting:
 roc: true
 loss: true
 score: true
 pt_dist: true
 pt_1dist: true

defaults:
 - model: gatr_reco
 - default
